### ISSUE TITLE
AMD module name definition generated the wrong format in WINDOWS computer

### ISSUE THREAD

**Issue by mattma** [phated/gulp-wrap-amd#11]
@Haroldchen used [ember-rocks](https://github.com/mattma/ember-rocks) in his **window** computer, and he submitted an [issue](https://github.com/mattma/ember-rocks/issues/9).

I narrow down the error and think it is something related [here](https://github.com/phated/gulp-wrap-amd/blob/master/index.js#L14-17). 

When the path is being modified, **window OS** is trying to backslash (\\) the filepath `/`. Has anyone reported this issue before? Could you help us here to address the issue? or correct me if I am wrong? :)

**Comment by phated** [comment]
You are correct.  Node uses the OS path characters anytime a `path` method is used.  This needs to be updated to replace [`path.delimiter`](http://nodejs.org/api/path.html#path_path_delimiter) with `/`

**Comment by phated** [comment]
Can you send a PR and test for this?

**Comment by mattma** [comment]
OK. I will. Thanks for the confirmation.

**Comment by phated** [comment]
Thanks for the patch!  The tests are passing on https://ci.appveyor.com/project/phated/gulp-wrap-amd/build/3 now too!
